services:
  workspace:
    # Build the image from the Dockerfile in the current directory
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile

    volumes:
      - ..:/workspace:cached

    tty: true

    environment:
      - PYTHONPATH=/workspace/modules
      - PYTHON_VERSION=3.12
      - PYTHONUNBUFFERED=1

    # Use "forwardPorts" in devcontainer.json to forward a port locally.
    # "runArgs": [ "--cap-add=SYS_PTRACE", "--security-opt", "seccomp=unconfined" ]

    develop:
      # Create a `watch` configuration to update the app
      # https://docs.docker.com/compose/file-watch/#compose-watch-versus-bind-mounts
      watch:
        # Sync the working directory with the `/workspace` directory in the container
        - action: sync
          path: ../
          target: /workspace
          # Exclude the project virtual environment — it could be for a
          # different platform in the container
          ignore:
            - .venv/
            - "**/__pycache__"
            - "**/*.pyc"
            - ".git/"
            - ".ruff_cache/"

        # Rebuild the image if dependencies change
        - action: rebuild
          path: ../uv.lock
