services:
  workspace:
    # Build the image from the Dockerfile in the current directory
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile

    volumes:
      - ..:/workspace:cached

    tty: true

    environment:
      - PYTHONPATH=/workspace:/workspace/modules:$PYTHONPATH
      - PYTHON_VERSION=3.12
      - PYTHONUNBUFFERED=1
